(TeX-add-style-hook "jss617"
 (lambda ()
    (LaTeX-add-bibliographies)
    (LaTeX-add-labels
     "tab:exdata"
     "sec:models-impl-unmark"
     "tab:models"
     "sec:occ"
     "sec:repeated-count-data"
     "eq:pc2"
     "sec:gener-mult-poiss"
     "eq:mp2"
     "sec:double-observ-sampl"
     "sec:distsamp"
     "sec:unmarked-usage"
     "sec:data-requirements"
     "sec:manip"
     "sec:fitting-models"
     "sec:examining-model-fits"
     "fig:pred"
     "fig:pb"
     "sec:future-direct-unmark"
     "tab:modspace")
    (TeX-add-symbols
     "um"
     "rlang"
     "scovs"
     "ocovs")
    (TeX-run-style-hooks
     "float"
     "rotating"
     "inputenc"
     "utf8"
     "amssymb"
     "amsmath"
     "latex2e"
     "jss10"
     "jss"
     "article"
     "shortnames")))

