<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Class "unmarkedFitList" — unmarkedFitList-class • unmarked</title>


<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<!-- Bootstrap -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script>

<!-- bootstrap-toc -->
<link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>

<!-- headroom.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>




<meta property="og:title" content="Class "unmarkedFitList" — unmarkedFitList-class" />
<meta property="og:description" content="Class to hold multiple fitted models from one of
	unmarked's fitting functions" />




<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->



  </head>

  <body data-spy="scroll" data-target="#toc">
    <div class="container template-reference-topic">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">unmarked</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.1.1.9021</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/rbchan/unmarked/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      

      </header>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header">
    <h1>Class "unmarkedFitList"</h1>
    
    <div class="hidden name"><code>unmarkedFitList-class.rd</code></div>
    </div>

    <div class="ref-description">
    <p>Class to hold multiple fitted models from one of
	<code>unmarked</code>'s fitting functions</p>
    </div>



    <h2 class="hasAnchor" id="objects-from-the-class"><a class="anchor" href="#objects-from-the-class"></a>Objects from the Class</h2>

    <p>Objects can be created by using the <code><a href='fitList.html'>fitList</a></code> function.</p>
    <h2 class="hasAnchor" id="slots"><a class="anchor" href="#slots"></a>Slots</h2>

    <p></p><dl>
    <dt><code>fits</code>:</dt><dd><p>A <code>"list"</code> of models.</p></dd>
  
</dl>

    <h2 class="hasAnchor" id="methods"><a class="anchor" href="#methods"></a>Methods</h2>

    <p></p><dl>
    <dt>coef</dt><dd><p><code>signature(object = "unmarkedFitList")</code>:
        Extract coefficients</p></dd>
    <dt>SE</dt><dd><p><code>signature(object = "unmarkedFitList")</code>:
        Extract standard errors</p></dd>
    <dt>modSel</dt><dd><p><code>signature(object = "unmarkedFitList")</code>:
		Model selection</p></dd>
    <dt>predict</dt><dd><p><code>signature(object = "unmarkedFitList")</code>:
		Model-averaged prediction</p></dd>
	 
</dl>

    <h2 class="hasAnchor" id="note"><a class="anchor" href="#note"></a>Note</h2>

    <p>Model-averaging regression coefficients is intentionally not implemented.</p>
    <h2 class="hasAnchor" id="see-also"><a class="anchor" href="#see-also"></a>See also</h2>

    <div class='dont-index'><p><code><a href='fitList.html'>fitList</a></code>,
	<code><a href='unmarkedFit-class.html'>unmarkedFit</a></code></p></div>

    <h2 class="hasAnchor" id="examples"><a class="anchor" href="#examples"></a>Examples</h2>
    <pre class="examples"><div class='input'><span class='fu'>showClass</span><span class='op'>(</span><span class='st'>"unmarkedFitList"</span><span class='op'>)</span>
</div><div class='output co'>#&gt; Class "unmarkedFitList" [package "unmarked"]
#&gt; 
#&gt; Slots:
#&gt;            
#&gt; Name:  fits
#&gt; Class: list</div><div class='input'>
<span class='fu'><a href='https://rdrr.io/r/utils/data.html'>data</a></span><span class='op'>(</span><span class='va'>linetran</span><span class='op'>)</span>
<span class='op'>(</span><span class='va'>dbreaksLine</span> <span class='op'>&lt;-</span> <span class='fu'><a href='https://rdrr.io/r/base/c.html'>c</a></span><span class='op'>(</span><span class='fl'>0</span>, <span class='fl'>5</span>, <span class='fl'>10</span>, <span class='fl'>15</span>, <span class='fl'>20</span><span class='op'>)</span><span class='op'>)</span>
</div><div class='output co'>#&gt; [1]  0  5 10 15 20</div><div class='input'><span class='va'>lengths</span> <span class='op'>&lt;-</span> <span class='va'>linetran</span><span class='op'>$</span><span class='va'>Length</span> <span class='op'>*</span> <span class='fl'>1000</span>

<span class='va'>ltUMF</span> <span class='op'>&lt;-</span> <span class='fu'><a href='https://rdrr.io/r/base/with.html'>with</a></span><span class='op'>(</span><span class='va'>linetran</span>, <span class='op'>{</span>
  <span class='fu'><a href='unmarkedFrameDS.html'>unmarkedFrameDS</a></span><span class='op'>(</span>y <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/cbind.html'>cbind</a></span><span class='op'>(</span><span class='va'>dc1</span>, <span class='va'>dc2</span>, <span class='va'>dc3</span>, <span class='va'>dc4</span><span class='op'>)</span>,
  siteCovs <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/data.frame.html'>data.frame</a></span><span class='op'>(</span><span class='va'>Length</span>, <span class='va'>area</span>, <span class='va'>habitat</span><span class='op'>)</span>, dist.breaks <span class='op'>=</span> <span class='va'>dbreaksLine</span>,
  tlength <span class='op'>=</span> <span class='va'>lengths</span>, survey <span class='op'>=</span> <span class='st'>"line"</span>, unitsIn <span class='op'>=</span> <span class='st'>"m"</span><span class='op'>)</span>
  <span class='op'>}</span><span class='op'>)</span>

<span class='va'>fm1</span> <span class='op'>&lt;-</span> <span class='fu'><a href='distsamp.html'>distsamp</a></span><span class='op'>(</span><span class='op'>~</span> <span class='fl'>1</span> <span class='op'>~</span><span class='fl'>1</span>, <span class='va'>ltUMF</span><span class='op'>)</span>
<span class='va'>fm2</span> <span class='op'>&lt;-</span> <span class='fu'><a href='distsamp.html'>distsamp</a></span><span class='op'>(</span><span class='op'>~</span> <span class='va'>area</span> <span class='op'>~</span><span class='fl'>1</span>, <span class='va'>ltUMF</span><span class='op'>)</span>
<span class='va'>fm3</span> <span class='op'>&lt;-</span> <span class='fu'><a href='distsamp.html'>distsamp</a></span><span class='op'>(</span> <span class='op'>~</span> <span class='fl'>1</span> <span class='op'>~</span><span class='va'>area</span>, <span class='va'>ltUMF</span><span class='op'>)</span>

<span class='va'>fl</span> <span class='op'>&lt;-</span> <span class='fu'><a href='fitList.html'>fitList</a></span><span class='op'>(</span>Null<span class='op'>=</span><span class='va'>fm1</span>, A.<span class='op'>=</span><span class='va'>fm2</span>, .A<span class='op'>=</span><span class='va'>fm3</span><span class='op'>)</span>
<span class='va'>fl</span>
</div><div class='output co'>#&gt; An object of class "unmarkedFitList"
#&gt; Slot "fits":
#&gt; $Null
#&gt; 
#&gt; Call:
#&gt; distsamp(formula = ~1 ~ 1, data = ltUMF)
#&gt; 
#&gt; Density:
#&gt;  Estimate    SE     z P(&gt;|z|)
#&gt;    -0.171 0.134 -1.28   0.201
#&gt; 
#&gt; Detection:
#&gt;  Estimate    SE    z  P(&gt;|z|)
#&gt;      2.39 0.127 18.7 2.46e-78
#&gt; 
#&gt; AIC: 164.7524 
#&gt; 
#&gt; $A.
#&gt; 
#&gt; Call:
#&gt; distsamp(formula = ~area ~ 1, data = ltUMF)
#&gt; 
#&gt; Density:
#&gt;  Estimate    SE     z P(&gt;|z|)
#&gt;    -0.168 0.134 -1.25    0.21
#&gt; 
#&gt; Detection:
#&gt;             Estimate     SE     z  P(&gt;|z|)
#&gt; (Intercept)     3.00 0.5402  5.56 2.72e-08
#&gt; area           -0.12 0.0955 -1.26 2.07e-01
#&gt; 
#&gt; AIC: 165.1845 
#&gt; 
#&gt; $.A
#&gt; 
#&gt; Call:
#&gt; distsamp(formula = ~1 ~ area, data = ltUMF)
#&gt; 
#&gt; Density:
#&gt;             Estimate     SE      z P(&gt;|z|)
#&gt; (Intercept)   0.2364 0.5123  0.462   0.644
#&gt; area         -0.0801 0.0979 -0.817   0.414
#&gt; 
#&gt; Detection:
#&gt;  Estimate    SE    z  P(&gt;|z|)
#&gt;      2.39 0.127 18.7 2.47e-78
#&gt; 
#&gt; AIC: 166.0759 
#&gt; 
#&gt; </div><div class='input'>
<span class='fu'><a href='https://rdrr.io/r/stats/coef.html'>coef</a></span><span class='op'>(</span><span class='va'>fl</span><span class='op'>)</span>
</div><div class='output co'>#&gt;        lam(Int)   p(Int)   p(area)   lam(area)
#&gt; Null -0.1710554 2.386380        NA          NA
#&gt; A.   -0.1678270 3.002507 -0.120364          NA
#&gt; .A    0.2364320 2.386386        NA -0.08005895</div><div class='input'><span class='fu'><a href='SE-methods.html'>SE</a></span><span class='op'>(</span><span class='va'>fl</span><span class='op'>)</span>
</div><div class='output co'>#&gt;       lam(Int)    p(Int)    p(area) lam(area)
#&gt; Null 0.1337819 0.1273598         NA        NA
#&gt; A.   0.1340212 0.5401575 0.09548038        NA
#&gt; .A   0.5122837 0.1273614         NA 0.0979427</div><div class='input'>
<span class='va'>ms</span> <span class='op'>&lt;-</span> <span class='fu'><a href='modSel.html'>modSel</a></span><span class='op'>(</span><span class='va'>fl</span>, nullmod<span class='op'>=</span><span class='st'>"Null"</span><span class='op'>)</span>
<span class='va'>ms</span>
</div><div class='output co'>#&gt;      nPars    AIC delta AICwt cumltvWt   Rsq
#&gt; Null     2 164.75  0.00  0.43     0.43 0.000
#&gt; A.       3 165.18  0.43  0.35     0.78 0.122
#&gt; .A       3 166.08  1.32  0.22     1.00 0.055</div><div class='input'>

</div></pre>
  </div>
  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">
    <nav id="toc" data-toggle="toc" class="sticky-top">
      <h2 data-toc-skip>Contents</h2>
    </nav>
  </div>
</div>


      <footer>
      <div class="copyright">
  <p>Developed by <a href='https://chandlerlab.uga.edu/richard-chandler-phd/'>Richard Chandler</a>, <a href='https://kenkellner.com'>Ken Kellner</a>, Ian Fiske, David Miller, Andy Royle, Jeff Hostetler, Rebecca Hutchinson, Adam Smith.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
   </div>

  


  </body>
</html>


